"""empty message
Revision ID: 0bf9f6f4014a
Revises: fbcdbbc11c4f
Create Date: 2019-02-14 19:07:07.093901
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bf9f6f4014a'
down_revision = 'fbcdbbc11c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('research_centre_ibfk_1', 'research_centre', type_='foreignkey')
    op.drop_column('research_centre', 'user_profile_id')
    op.drop_constraint('user_profile_ibfk_1', 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'login_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('login_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_profile_ibfk_1', 'user_profile', 'researcher', ['login_id'], ['researcher_id'])
    op.add_column('research_centre', sa.Column('user_profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('research_centre_ibfk_1', 'research_centre', 'user_profile', ['user_profile_id'], ['user_id'])
    # ### end Alembic commands ###