"""empty message

Revision ID: 1b6248d5bf9d
Revises: fe8a1ee2d17a
Create Date: 2019-02-26 19:47:50.647960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6248d5bf9d'
down_revision = 'fe8a1ee2d17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_applications',
    sa.Column('grant_application_id', sa.Integer(), nullable=False),
    sa.Column('proposal_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('grant_application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_applications')
    # ### end Alembic commands ###
