"""empty message

Revision ID: 1e4a12cce4db
Revises: 674fc1207686
Create Date: 2019-03-06 16:36:15.857538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4a12cce4db'
down_revision = '674fc1207686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impacts', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'impacts', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'impacts', type_='foreignkey')
    op.drop_column('impacts', 'users')
    # ### end Alembic commands ###
