"""empty message

Revision ID: 1ffb6ceffcb8
Revises: 99b03641ca8d
Create Date: 2019-02-15 23:47:56.700153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffb6ceffcb8'
down_revision = '99b03641ca8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_db',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('institution', sa.String(length=25), nullable=True),
    sa.Column('location', sa.String(length=21), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('employment_id')
    )
    op.create_table('funding_diversifications',
    sa.Column('funding_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('funding_amount', sa.Integer(), nullable=True),
    sa.Column('funding_body', sa.String(length=64), nullable=True),
    sa.Column('funding_programme', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('primary_attribution', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('funding_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_diversifications')
    op.drop_table('employment_db')
    # ### end Alembic commands ###
