"""empty message

Revision ID: 201a0e76c25a
Revises: 9bd648007154
Create Date: 2019-02-24 15:38:44.300162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '201a0e76c25a'
down_revision = '9bd648007154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_application',
    sa.Column('grant_application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('proposalTitle', sa.String(length=30), nullable=True),
    sa.Column('awardDuration', sa.String(length=30), nullable=True),
    sa.Column('nationalResearchPriority', sa.String(length=60), nullable=True),
    sa.Column('sfiLegalRemitJustification', sa.String(length=2000), nullable=True),
    sa.Column('ethicalIssues', sa.String(length=200), nullable=True),
    sa.Column('applicantsCountry', sa.String(length=40), nullable=True),
    sa.Column('scientificAbstract', sa.String(length=2000), nullable=True),
    sa.Column('layAbstract', sa.String(length=1000), nullable=True),
    sa.Column('programmeDocuments', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('grant_application_id')
    )
    op.create_table('co__applicants',
    sa.Column('coapplicant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('organization', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('grant_application', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grant_application'], ['grant_application.grant_application_id'], ),
    sa.PrimaryKeyConstraint('coapplicant_id')
    )
    op.create_table('collaborators',
    sa.Column('collabarator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('organization', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('grant_application', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grant_application'], ['grant_application.grant_application_id'], ),
    sa.PrimaryKeyConstraint('collabarator_id')
    )
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('posted', mysql.DATETIME(), nullable=True),
    sa.Column('commenter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], name='comments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('collaborators')
    op.drop_table('co__applicants')
    op.drop_table('grant_application')
    # ### end Alembic commands ###
