"""empty message

Revision ID: 20e384b7d8b7
Revises: e9cd248f99d9
Create Date: 2019-02-15 16:15:53.782998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e384b7d8b7'
down_revision = 'e9cd248f99d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_centre_admin', sa.Column('loginID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'research_centre_admin', 'login_account', ['loginID'], ['login_account_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_centre_admin', type_='foreignkey')
    op.drop_column('research_centre_admin', 'loginID')
    # ### end Alembic commands ###
