"""empty message

Revision ID: 219276cb33f8
Revises: dff61051b3ec
Create Date: 2019-02-13 17:49:32.369035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '219276cb33f8'
down_revision = 'dff61051b3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tester')
    op.drop_column('users', 'online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tester', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
