"""empty message

Revision ID: 225175b9fb00
Revises: 0bf9f6f4014a
Create Date: 2019-02-14 20:14:46.858365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '225175b9fb00'
down_revision = '0bf9f6f4014a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_centre', sa.Column('research_centre_id', sa.Integer(), nullable=False))
    op.drop_column('research_centre', 'researcher_centre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_centre', sa.Column('researcher_centre_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('research_centre', 'research_centre_id')
    # ### end Alembic commands ###
