"""empty message

Revision ID: 2b36e5565438
Revises: ac5647e3093a
Create Date: 2019-03-06 14:54:47.626204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b36e5565438'
down_revision = 'ac5647e3093a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'communication', 'users', ['users'], ['id'])
    op.add_column('innovations', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'innovations', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'innovations', type_='foreignkey')
    op.drop_column('innovations', 'users')
    op.drop_constraint(None, 'communication', type_='foreignkey')
    op.drop_column('communication', 'users')
    # ### end Alembic commands ###
