"""empty message

Revision ID: 3faf18ed8fea
Revises: a1d3b74f2147
Create Date: 2019-03-10 13:22:40.454340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faf18ed8fea'
down_revision = 'a1d3b74f2147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals_accepted',
    sa.Column('accepted_id', sa.Integer(), nullable=False),
    sa.Column('grant_number', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('began', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['grant_number'], ['grant_application.grant_application_id'], ),
    sa.PrimaryKeyConstraint('accepted_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals_accepted')
    # ### end Alembic commands ###
