"""empty message

Revision ID: 45e10267bc5b
Revises: 2f35e09b410e
Create Date: 2019-03-06 15:49:08.111328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e10267bc5b'
down_revision = '2f35e09b410e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_societies', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professional_societies', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professional_societies', type_='foreignkey')
    op.drop_column('professional_societies', 'users')
    # ### end Alembic commands ###
