"""empty message

Revision ID: 4845fdf67e72
Revises: a8a837ee8801
Create Date: 2019-02-16 01:20:02.115532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4845fdf67e72'
down_revision = 'a8a837ee8801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_reports',
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('academic_collab_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('non_academic_collab_id', sa.Integer(), nullable=True),
    sa.Column('impact_id', sa.Integer(), nullable=True),
    sa.Column('innovations_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_collab_id'], ['academic_collaborations.collaboration_id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['researcher_education.researcher_education_id'], ),
    sa.ForeignKeyConstraint(['impact_id'], ['impacts.impact_id'], ),
    sa.ForeignKeyConstraint(['innovations_id'], ['innovations.innovation_id'], ),
    sa.ForeignKeyConstraint(['non_academic_collab_id'], ['non_academic_collaborations.non_academic_collaboration_id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], ),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('annual_report_id')
    )
    op.drop_table('annual reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual reports',
    sa.Column('annual_report_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('research_Profile', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('publication_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('academic_collab_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('education_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('non_academic_collab_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('impact_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('innovations_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['academic_collab_id'], ['academic_collaborations.collaboration_id'], name='annual reports_ibfk_1'),
    sa.ForeignKeyConstraint(['education_id'], ['researcher_education.researcher_education_id'], name='annual reports_ibfk_2'),
    sa.ForeignKeyConstraint(['impact_id'], ['impacts.impact_id'], name='annual reports_ibfk_3'),
    sa.ForeignKeyConstraint(['innovations_id'], ['innovations.innovation_id'], name='annual reports_ibfk_4'),
    sa.ForeignKeyConstraint(['non_academic_collab_id'], ['non_academic_collaborations.non_academic_collaboration_id'], name='annual reports_ibfk_5'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], name='annual reports_ibfk_6'),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], name='annual reports_ibfk_7'),
    sa.PrimaryKeyConstraint('annual_report_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('annual_reports')
    # ### end Alembic commands ###
