"""empty message

Revision ID: 5b26395b3572
Revises: 5b5f04c0c807
Create Date: 2019-03-03 15:49:25.502050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b26395b3572'
down_revision = '5b5f04c0c807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_application', sa.Column('reviewer_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_application', 'reviewer_approved')
    # ### end Alembic commands ###
