"""empty message

Revision ID: 5b5f04c0c807
Revises: 3d689170db0d
Create Date: 2019-03-03 03:54:54.530330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5f04c0c807'
down_revision = '3d689170db0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_application', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_application', 'approved')
    # ### end Alembic commands ###
