"""empty message

Revision ID: 674fc1207686
Revises: c4d479a0b95a
Create Date: 2019-03-06 16:06:54.162107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674fc1207686'
down_revision = 'c4d479a0b95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_diversifications', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'funding_diversifications', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funding_diversifications', type_='foreignkey')
    op.drop_column('funding_diversifications', 'users')
    # ### end Alembic commands ###
