"""empty message

Revision ID: 6d4081743525
Revises: 2b36e5565438
Create Date: 2019-03-06 15:02:36.451418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4081743525'
down_revision = '2b36e5565438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_ratio', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'funding_ratio', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funding_ratio', type_='foreignkey')
    op.drop_column('funding_ratio', 'users')
    # ### end Alembic commands ###
