"""empty message

Revision ID: 6ee880ead831
Revises: b34d805c140a
Create Date: 2019-02-15 22:51:25.411503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee880ead831'
down_revision = 'b34d805c140a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('f_name', sa.String(length=64), nullable=True),
    sa.Column('l_name', sa.String(length=64), nullable=True),
    sa.Column('job_title', sa.String(length=4), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('ORCID', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('loginID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loginID'], ['login_account.login_account_id'], ),
    sa.PrimaryKeyConstraint('engagement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagements')
    # ### end Alembic commands ###
