"""empty message

Revision ID: 6f19a701edc5
Revises: 6ee880ead831
Create Date: 2019-02-15 23:02:03.353639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f19a701edc5'
down_revision = '6ee880ead831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('research_Profile', sa.Integer(), nullable=True))
    op.drop_constraint('engagements_ibfk_1', 'engagements', type_='foreignkey')
    op.create_foreign_key(None, 'engagements', 'researcher_profile', ['research_Profile'], ['researcher_id'])
    op.drop_column('engagements', 'loginID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('loginID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.create_foreign_key('engagements_ibfk_1', 'engagements', 'login_account', ['loginID'], ['login_account_id'])
    op.drop_column('engagements', 'research_Profile')
    # ### end Alembic commands ###
