"""empty message

Revision ID: 78ecabbc10a0
Revises: 42c73082ba66
Create Date: 2019-03-04 01:13:43.593884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ecabbc10a0'
down_revision = '42c73082ba66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('non_academic_collaborations', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'non_academic_collaborations', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'non_academic_collaborations', type_='foreignkey')
    op.drop_column('non_academic_collaborations', 'users')
    # ### end Alembic commands ###
