"""empty message

Revision ID: 8347147023a3
Revises: 4845fdf67e72
Create Date: 2019-02-16 01:51:59.671762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8347147023a3'
down_revision = '4845fdf67e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_for_proposals',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('text_of_call', sa.String(length=300), nullable=True),
    sa.Column('target_audience', sa.String(length=30), nullable=True),
    sa.Column('eligibility_criteria', sa.String(length=60), nullable=True),
    sa.Column('duration_of_award', sa.String(length=30), nullable=True),
    sa.Column('reporting_guidelines', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('call_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_for_proposals')
    # ### end Alembic commands ###
