"""empty message

Revision ID: 94e78eeb1a17
Revises: 78ecabbc10a0
Create Date: 2019-03-04 01:15:38.339420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e78eeb1a17'
down_revision = '78ecabbc10a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_education', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'researcher_education', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'researcher_education', type_='foreignkey')
    op.drop_column('researcher_education', 'users')
    # ### end Alembic commands ###
