"""empty message

Revision ID: 99b03641ca8d
Revises: 4d4ed91a0f04
Create Date: 2019-02-15 23:30:56.771582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b03641ca8d'
down_revision = '4d4ed91a0f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impacts',
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('impact_title', sa.String(length=38), nullable=True),
    sa.Column('impact_category', sa.String(length=38), nullable=True),
    sa.Column('primary_beneficiary', sa.String(length=38), nullable=True),
    sa.Column('primary_attribution', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('impact_id')
    )
    op.create_table('team_members',
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('grant_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('team_member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_table('impacts')
    # ### end Alembic commands ###
