"""empty message

Revision ID: a0cfe53e4762
Revises: 219276cb33f8
Create Date: 2019-02-13 18:02:26.880381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0cfe53e4762'
down_revision = '219276cb33f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sfiAdmin',
    sa.Column('sfi_admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('sfi_admin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sfiAdmin')
    # ### end Alembic commands ###
