"""empty message

Revision ID: a1d3b74f2147
Revises: 1e4a12cce4db
Create Date: 2019-03-06 16:42:21.074817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d3b74f2147'
down_revision = '1e4a12cce4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'presentations', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presentations', type_='foreignkey')
    op.drop_column('presentations', 'users')
    # ### end Alembic commands ###
