"""empty message

Revision ID: a8a837ee8801
Revises: d281a4038d1a
Create Date: 2019-02-16 01:17:10.534160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a837ee8801'
down_revision = 'd281a4038d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual reports',
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('academic_collab_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('non_academic_collab_id', sa.Integer(), nullable=True),
    sa.Column('impact_id', sa.Integer(), nullable=True),
    sa.Column('innovations_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_collab_id'], ['academic_collaborations.collaboration_id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['researcher_education.researcher_education_id'], ),
    sa.ForeignKeyConstraint(['impact_id'], ['impacts.impact_id'], ),
    sa.ForeignKeyConstraint(['innovations_id'], ['innovations.innovation_id'], ),
    sa.ForeignKeyConstraint(['non_academic_collab_id'], ['non_academic_collaborations.non_academic_collaboration_id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], ),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('annual_report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annual reports')
    # ### end Alembic commands ###
