"""empty message

Revision ID: c4d479a0b95a
Revises: 45e10267bc5b
Create Date: 2019-03-06 15:58:22.727321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d479a0b95a'
down_revision = '45e10267bc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards_db', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'awards_db', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'awards_db', type_='foreignkey')
    op.drop_column('awards_db', 'users')
    # ### end Alembic commands ###
