"""empty message

Revision ID: cf437813bd4a
Revises: e15582747147
Create Date: 2019-02-13 18:12:33.233445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf437813bd4a'
down_revision = 'e15582747147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_centre',
    sa.Column('researcher_centre_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('online', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('researcher_centre_id')
    )
    op.create_table('researcher',
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    op.add_column('reviewer', sa.Column('reviewer_id', sa.Integer(), nullable=False))
    op.drop_column('reviewer', 'sfi_admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewer', sa.Column('sfi_admin_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('reviewer', 'reviewer_id')
    op.drop_table('researcher')
    op.drop_table('research_centre')
    # ### end Alembic commands ###
