"""empty message

Revision ID: d0f15ee01d1a
Revises: 5297021ac20d
Create Date: 2019-02-28 12:00:31.605846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0f15ee01d1a'
down_revision = '5297021ac20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaborators', sa.Column('collaborator_id', sa.Integer(), nullable=False))
    op.drop_column('collaborators', 'collabarator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaborators', sa.Column('collabarator_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('collaborators', 'collaborator_id')
    # ### end Alembic commands ###
