"""empty message

Revision ID: d281a4038d1a
Revises: e1cc66122fe1
Create Date: 2019-02-16 00:44:17.726554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd281a4038d1a'
down_revision = 'e1cc66122fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('innovations',
    sa.Column('innovation_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=25), nullable=True),
    sa.Column('grant_number', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('innovation_id')
    )
    op.create_table('researcher_education',
    sa.Column('researcher_education_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('field_of_study', sa.String(length=35), nullable=True),
    sa.Column('degree', sa.String(length=20), nullable=True),
    sa.Column('institution', sa.String(length=20), nullable=True),
    sa.Column('year_of_degree', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('researcher_education_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researcher_education')
    op.drop_table('innovations')
    # ### end Alembic commands ###
