"""empty message

Revision ID: d8fbb6ec0214
Revises: 6d4081743525
Create Date: 2019-03-06 15:21:38.828669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fbb6ec0214'
down_revision = '6d4081743525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team_members', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'users')
    # ### end Alembic commands ###
