"""empty message

Revision ID: e1cc66122fe1
Revises: 66eb78fa61a0
Create Date: 2019-02-16 00:24:01.031743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cc66122fe1'
down_revision = '66eb78fa61a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_collaborations',
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('institution_name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('collaborator_name', sa.String(length=40), nullable=True),
    sa.Column('collaborator_goal', sa.String(length=40), nullable=True),
    sa.Column('interaction_frequency', sa.String(length=40), nullable=True),
    sa.Column('grant_number', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('collaboration_id')
    )
    op.create_table('communication',
    sa.Column('research_profile_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('num_lectures', sa.Integer(), nullable=True),
    sa.Column('num_visits', sa.Integer(), nullable=True),
    sa.Column('num_media_interactions', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('research_profile_id')
    )
    op.create_table('conferences',
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('event_location', sa.String(length=30), nullable=True),
    sa.Column('grant_num', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('conference_id')
    )
    op.create_table('non_academic_collaborations',
    sa.Column('non_academic_collaboration_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('collaborator_name', sa.String(length=40), nullable=True),
    sa.Column('collaborator_goal', sa.String(length=40), nullable=True),
    sa.Column('interaction_frequency', sa.String(length=40), nullable=True),
    sa.Column('grant_number', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('non_academic_collaboration_id')
    )
    op.create_table('professional_socities',
    sa.Column('research_profile_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('membership_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('research_profile_id')
    )
    op.create_table('publications',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('journal_conference_name', sa.String(length=64), nullable=True),
    sa.Column('published', sa.BOOLEAN(), nullable=True),
    sa.Column('in_press', sa.BOOLEAN(), nullable=True),
    sa.Column('doi', sa.Integer(), nullable=True),
    sa.Column('grant_num', sa.Integer(), nullable=True),
    sa.Column('research_Profile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_Profile'], ['researcher_profile.researcher_id'], ),
    sa.PrimaryKeyConstraint('publication_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('professional_socities')
    op.drop_table('non_academic_collaborations')
    op.drop_table('conferences')
    op.drop_table('communication')
    op.drop_table('academic_collaborations')
    # ### end Alembic commands ###
