"""empty message

Revision ID: e29f955b6c89
Revises: 5b26395b3572
Create Date: 2019-03-04 01:04:29.614174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29f955b6c89'
down_revision = '5b26395b3572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_profile', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('researcher_profile', sa.Column('phone_extension', sa.Integer(), nullable=True))
    op.add_column('researcher_profile', sa.Column('prefix', sa.String(length=10), nullable=True))
    op.add_column('researcher_profile', sa.Column('suffix', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher_profile', 'suffix')
    op.drop_column('researcher_profile', 'prefix')
    op.drop_column('researcher_profile', 'phone_extension')
    op.drop_column('researcher_profile', 'phone')
    # ### end Alembic commands ###
