"""empty message

Revision ID: e9cd248f99d9
Revises: 0a4ff2503131
Create Date: 2019-02-15 12:39:26.068721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9cd248f99d9'
down_revision = '0a4ff2503131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_account',
    sa.Column('login_account_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('login_account_id')
    )
    op.create_table('research_centre_admin',
    sa.Column('research_centre_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('research_profile', sa.Integer(), nullable=True),
    sa.Column('online', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('research_centre_id')
    )
    op.create_table('researcher_account',
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    op.create_table('researcher_profile',
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('f_name', sa.String(length=64), nullable=True),
    sa.Column('l_name', sa.String(length=64), nullable=True),
    sa.Column('job_title', sa.String(length=4), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('ORCID', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    op.drop_table('user_profile')
    op.drop_table('research_centre')
    op.drop_table('researcher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher',
    sa.Column('researcher_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('ORCID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('f_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('job_title', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('l_name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('researcher_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('research_centre',
    sa.Column('research_centre_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('research_centre_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_profile',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('researcher_profile')
    op.drop_table('researcher_account')
    op.drop_table('research_centre_admin')
    op.drop_table('login_account')
    # ### end Alembic commands ###
