"""empty message

Revision ID: fbcdbbc11c4f
Revises: dd2ab985218f
Create Date: 2019-02-14 19:03:55.498817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcdbbc11c4f'
down_revision = 'dd2ab985218f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('login_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_profile', 'researcher', ['login_id'], ['researcher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'login_id')
    # ### end Alembic commands ###
