"""empty message

Revision ID: ffb9f9eb2f0c
Revises: 20e384b7d8b7
Create Date: 2019-02-15 16:23:04.467952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb9f9eb2f0c'
down_revision = '20e384b7d8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sfiAdmin', sa.Column('loginID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sfiAdmin', 'login_account', ['loginID'], ['login_account_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sfiAdmin', type_='foreignkey')
    op.drop_column('sfiAdmin', 'loginID')
    # ### end Alembic commands ###
